### ISSUE TITLE
add defaults by tracker

### ISSUE THREAD

**Issue by darioo** [edosoft/redmine-inherit-fields-plugin#2]
this plugun is simple but usefull. for me it would by nice to have option to set defaults per tracker. We are using scrum and we use few trackers:
epic - main
story , subtask of epic
task - subtask of story

we also have
test scenario, test case subtask of test scenario, bug subtask of test case

as you see settungs for each tracker will be useful

thankyou
darioo

**Comment by Kerian-NOEL** [comment]
Hello. Is this enhancement on progress? It's been 4 months, and there's no information, so I'd like to know if it has been abandonned or not.

**Comment by danielvijge** [comment]
I've created a new plugin, based on this plugin that does exactly what darioo requests. It allow to set a default tracker for subtasks per tracker. There is also an option to disable subtasks for a tracker.
It only changes or disables the links to create subtasks. So it is still possible to change the tracker type of a subtask. And it is still possible to set a parent, even if subtasks are disable for that parent's tracker type.
Because it overwrites the same function ( link_to_new_subtask() ) as the inherit fields plugin, I'm not sure if both plugins can be used in the same installation. I have not tested this.
You can download the plugin from https://github.com/danielvijge/redmine_default_subtask_tracker Please see [Issue 1](https://github.com/danielvijge/redmine_default_subtask_tracker/issues/1) when installing the plugin for the first time.
